openai:
#  api_key: ""
  api_key: "sk-a83be43ee33544f186e5fd7b5dab2ca8"
#  base_url: "https://api.openai.com/v1"
  base_url: "https://api.deepseek.com"
#  model: "gpt-4o-mini"
  model: "deepseek-chat"
  temperature: 0.2
  timeout_seconds: 60

otel:
  service_name: "openmanus-go"
  stdout: true

log:
  level: "info"

persistence:
  path: "/data/openmanus.db"

observability:
  enable_pprof: true
  enable_metrics: true
