# OpenManus-Go Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'openmanus'
    environment: 'development'

# Rules and alerts
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # OpenManus-Go application
  - job_name: 'openmanus-go'
    static_configs:
      - targets: ['openmanus:8080']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # MySQL metrics (if mysql_exporter is available)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql_exporter:9104']
  #   scrape_interval: 30s

  # Node exporter (system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
  #   scrape_interval: 30s

  # cAdvisor (container metrics)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   scrape_interval: 30s

  # Nginx metrics (if nginx_exporter is available)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx_exporter:9113']
  #   scrape_interval: 30s

  # Elasticsearch metrics (if available)
  # - job_name: 'elasticsearch'
  #   static_configs:
  #     - targets: ['elasticsearch_exporter:9114']
  #   scrape_interval: 30s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500
